name: wordpress

services:
  wordpress:
    extends:
      file: ./docker-compose-wordpress.yml
      service: wordpress
    environment:
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_ENVIRONMENT_TYPE', 'local');

  db:
    extends:
      file: ./docker-compose-wordpress.yml
      service: db

volumes:
  wordpress:
  db:
